[colors.cursor]
cursor = "0xffffff"
text = "0x000000"

[colors.primary]
background = "#000000"  # Fondo negro
foreground = "0xe0e0e0"  # Texto gris claro

[font]
size = 13.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
opacity = 1.0  # Transparencia más sutil

[window.padding]
x = 25
y = 15

[cursor]
style = "Beam"
[terminal]










