#!/bin/sh
# ===============================================
#       ⠀⠀⢀⣴⣿⣷⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
#       ⠀⢠⣿⣿⢿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
#       ⢀⡾⠋⠀⣰⣿⣿⠻⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
#       ⠘⠀⠀⢠⣿⣿⠃⠀⠈⠻⣿⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
#       ⠀⠀⠀⢸⣿⡇⠀⠀⠀⣼⣉⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣀⠀
#       ⠀⠀⠀⢹⣿⡇⠀⠀⠀⣿⣿⣿⣿⣿⣷⡄⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⠟⣿⠉⠁
#       ⠀⠀⠀⠸⣿⣿⣄⠀⠀⠘⢿⣿⡵⠋⠙⢿⣦⡀⠀⠀⣤⣠⠀⣠⣿⡅⠀⣿⠀⠀
#       ⠀⠀⠀⠀⠈⠻⢿⣿⣶⣤⣄⣀⠀⠀⠀⠈⠻⣷⣄⣠⣿⣿⡼⠋⠛⣡⡼⠋⠀⠀
#       ⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⠛⠻⠿⠿⠷⠶⠶⠾⣿⡿⠋⠻⣟⠉⠁⠀⠀⠀⠀⠀
#       ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡠⠶⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# Author: g3k
# Rep: https://github.com/IamGenarov/blackbspwm
# ===============================================

# -------------------------
# Environment
# -------------------------
export PATH="$HOME/.config/bspwm/scripts:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'
export _JAVA_AWT_WM_NONREPARENTING=1

# -------------------------
# Monitors & Desktops
# -------------------------
bspc monitor -d I II III IV V

# -------------------------
# BSPWM Configuration
# -------------------------
bspc config top_padding           5
bspc config bottom_padding        5
bspc config right_padding         5
bspc config left_padding          83

bspc config split_ratio           0.53
bspc config single_monocle        true
bspc config automatic_scheme      longest_side
bspc config initial_polarity      second_child
bspc config removal_adjustment    true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true
bspc config pointer_motion_interval 7
bspc config pointer_modifier      mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner
bspc config border_width          0

bspc rule -a FloatingTerm state=floating center=true
bspc config external_rules_command "${HOME}/.config/bspwm/scripts/Rules"

# -------------------------
# Helper Function
# -------------------------
run() {
  if ! pidof -q "$1"; then
    "$@" &
  fi
}

# -------------------------
# Launch Applications
# -------------------------
# Hotkeys
run sxhkd -c "${HOME}/.config/sxhkd/sxhkdrc"

# Notifications
pkill dunst
sleep 0.2
dunst -conf "${HOME}/.config/dunst/dunstrc" &

# Eww Bar
eww daemon --config "${HOME}/.config/eww"
sleep 1
eww open bar --config "${HOME}/.config/eww" --arg monitor="$(bspc query -M --names | head -n 1)"

xautolock -time 3 -locker "i3lock \
  --insidever-color=#44475add \
  --insidewrong-color=#44475add \
  --inside-color=#44475add \
  --ringver-color=#50fa7bdd \
  --ringwrong-color=#ff5555dd \
  --ring-color=#6272a4dd \
  --line-uses-ring \
  --keyhl-color=#ff79c6dd \
  --bshl-color=#ffb86cdd \
  --separator-color=#44475add \
  --verif-color=#50fa7b \
  --wrong-color=#ff5555 \
  --modif-color=#ff5555 \
  --layout-color=#6272a4 \
  --date-color=#6272a4 \
  --time-color=#6272a4 \
  --screen 1 \
  --blur 1 \
  --clock \
  --indicator \
  --time-str='%H:%M:%S' \
  --date-str='%A %e %B %Y' \
  --verif-text='Checking...' \
  --wrong-text='Wrong pswd' \
  --noinput='No Input' \
  --lock-text='Locking...' \
  --lockfailed='Lock Failed' \
  --radius=120 \
  --ring-width=10 \
  --pass-media-keys \
  --pass-screen-keys \
  --pass-volume-keys" &


# Picom with delay to avoid black screen
(sleep 1 && picom --config "${HOME}/.config/picom/picom.conf") &


# Wallpaper
feh --bg-fill "${HOME}/.config/wallpapers/g333k.png"
