#!/bin/sh
# =============================================================
#       ⠀⠀⢀⣴⣿⣷⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
#       ⠀⢠⣿⣿⢿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
#       ⢀⡾⠋⠀⣰⣿⣿⠻⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
#       ⠘⠀⠀⢠⣿⣿⠃⠀⠈⠻⣿⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
#       ⠀⠀⠀⢸⣿⡇⠀⠀⠀⣼⣉⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣀⠀
#       ⠀⠀⠀⢹⣿⡇⠀⠀⠀⣿⣿⣿⣿⣿⣷⡄⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⠟⣿⠉⠁
#       ⠀⠀⠀⠸⣿⣿⣄⠀⠀⠘⢿⣿⡵⠋⠙⢿⣦⡀⠀⠀⣤⣠⠀⣠⣿⡅⠀⣿⠀⠀
#       ⠀⠀⠀⠀⠈⠻⢿⣿⣶⣤⣄⣀⠀⠀⠀⠈⠻⣷⣄⣠⣿⣿⡼⠋⠛⣡⡼⠋⠀⠀
#       ⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⠛⠻⠿⠿⠷⠶⠶⠾⣿⡿⠋⠻⣟⠉⠁⠀⠀⠀⠀⠀
#       ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡠⠶⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# Autor: g3k
# Repo: https://github.com/IamGenarov/blackbspwm
# =============================================================


# ╭──────────────────────────────────────────────╮
# │        Escritorios y movimiento de ventanas  │
# ╰──────────────────────────────────────────────╯

# Cambiar a escritorio 1–5
super + {1-5}
    bspc desktop -f ^{1-5}

# Mover ventana al escritorio 1–5
super + shift + {1-5}
    bspc node -d ^{1-5}


# ╭──────────────────────────────────────────────╮
# │                Aplicaciones                  │
# ╰──────────────────────────────────────────────╯
# Click derecho para abrir jgmenu
#~button3
#  xqp 0 $(xdo id -N Bspwm -n root) && jgmenu --csv-file=~/.config/bspwm/src/config/jgmenu.txt --config-file=~/.config/bspwm/src/config/jgmenurc

#~button3
#  xqp 0 $(xdo id -N Bspwm -n root) && eval $(xdotool getmouselocation --shell) && jgmenu --no-standalone --at=$X,$Y --csv-file=$HOME/.config/bspwm/scripts/jgmenu.txt --config-file=$HOME/.config/bspwm/scripts/jgmenurc
#~button3
#  xqp 0 $(xdo id -N Bspwm -n root) && eval $(xdotool getmouselocation --shell) && jgmenu --no-standalone --at=$X,$Y --csv-file=$HOME/.config/bspwm/scripts/jgmenu.txt --config-file=$HOME/.config/bspwm/scripts/jgmenurc
~button3
  xqp 0 $(xdo id -N Bspwm -n root) && eval $(xdotool getmouselocation --shell) && jgmenu --no-standalone --at=$X,$Y --csv-file=$HOME/.config/bspwm/scripts/jgmenu.txt --config-file=$HOME/.config/bspwm/scripts/jgmenurc


# Terminal (Normal y flotante)
super + Return
    sh -c 'cd ~ && exec alacritty'

# Editor de configuración (Rice)
super + r
    RiceEditor

# HTB VPN - Terminal flotante
super + 6
    alacritty --class FloatingTerm -e ~/.config/bspwm/scripts/HTB

# Lanzar BurpSuite personalizado
super + 7
    ~/.config/bspwm/scripts/Burpsuite
super + 8
    ~/.config/bspwm/scripts/workspace
# ╭──────────────────────────────────────────────╮
# │                 Capturas                     │
# ╰──────────────────────────────────────────────╯

# Captura completa
super + s
    flameshot full -p ~/Pictures/Clipboard && pkill flameshot

# Captura con selector GUI
super + shift + s
    flameshot gui & sleep 10 && pkill flameshot


# ╭──────────────────────────────────────────────╮
# │       Apagar, reiniciar, cerrar sesión       │
# ╰──────────────────────────────────────────────╯
ctrl + super + alt + {p,r,q,l,k,s}
    {systemctl poweroff, systemctl reboot, bspc quit, ScreenLocker, xkill, SoftReload}


# ╭──────────────────────────────────────────────╮
# │      Control de brillo y volumen             │
# ╰──────────────────────────────────────────────╯

# Brillo
XF86MonBrightness{Up,Down}
    sh Brightness {up,down}

# Volumen
XF86Audio{RaiseVolume,LowerVolume,Mute}
    Volume{ --inc, --dec, --toggle}


# ╭──────────────────────────────────────────────╮
# │                 BSPWM Core                   │
# ╰──────────────────────────────────────────────╯

# Recargar BSPWM
super + alt + r
    bspc wm -r

# Cerrar/Killear nodo
super + x
    bspc node -c


# ╭──────────────────────────────────────────────╮
# │        Navegación y gestión de nodos         │
# ╰──────────────────────────────────────────────╯

# Rotar ventana
ctrl + Tab
    bspc node @/ --rotate {90,-90}

# Cambiar de escritorio (prev/next)
super + {Left,Right}
    bspc desktop -f {prev,next}


# ╭──────────────────────────────────────────────╮
# │          Menú de aplicaciones (Rofi)         │
# ╰──────────────────────────────────────────────╯

super + d
    rofi -show drun -theme $HOME/.config/rofi/config.rasi


# ╭──────────────────────────────────────────────╮
# │     Funciones múltiples para ventanas        │
# ╰──────────────────────────────────────────────╯

# Cerrar todas las ventanas del escritorio actual
super + ctrl + x
    bspc query -N -d | xargs -I id -n 1 bspc node id -c
