#!/bin/sh

get_ip_for_interface() {
    ip -4 addr show "$1" | awk '/inet / {print $2}' | cut -d/ -f1
}

ICON="images/no-wifi.png"
STATUS="Offline"

# Verificamos conectividad
if ip route get 1.1.1.1 >/dev/null 2>&1; then

    # ❶ VPN HackTheBox
    if ip -4 addr show tun0 2>/dev/null | grep -q "inet "; then
        ICON="images/htb.jpg"
        IP=$(get_ip_for_interface tun0)
        STATUS="HackTheBox - $IP"

    # ❷ Ethernet (e*) con IP asignada
    elif ip -4 addr show enp1s0 2>/dev/null | grep -q "inet "; then
        ICON="images/ethernet.png"
        IP=$(get_ip_for_interface enp1s0)
        STATUS="Ethernet - $IP"

    # ❸ Wi-Fi (w*) con IP asignada
    elif ip -4 addr show wlan0 2>/dev/null | grep -q "inet "; then
        ICON="images/wifi.png"
        SSID=$(iwgetid -r)
        IP=$(get_ip_for_interface wlan0)
        STATUS="${SSID:-WiFi} - $IP"
    # Internet VMWARE
    elif ip -4 addr show ens33 2>/dev/null | grep -q "inet "; then
	ICON="images/ethernet.png"
	IP=$(get_ip_for_interface ens33)
	STATUS="VMware - $IP"
    fi
fi

case "$1" in
    --stat) echo "$STATUS" ;;
    --icon) echo "$ICON" ;;
esac
