#!/bin/bash
WORKDIR="$HOME/CTF"

# Crear el directorio del proyecto si no existe
mkdir -p "$WORKDIR"

# --- Escritorio 1: 2 terminales horizontales ---
bspc desktop -f ^1
sh -c 'cd ~ && exec st -e tmux' &
sleep 1

# --- Escritorio 2: 1 terminal ---
bspc desktop -f ^2
sh -c 'cd ~ && exec st -e tmux' &
sleep 1

# --- Escritorio 3: Firefox sin URL ---
bspc desktop -f ^3
firefox & 
sleep 2

# --- Escritorio 4: BurpSuite ---
bspc desktop -f ^4
burpsuite &
sleep 2

# --- Escritorio 5: Neovim en carpeta de proyectos ---
bspc desktop -f ^5
st -e bash -c "cd \"$WORKDIR\" && nvim" &
sleep 2

# --- Volver al escritorio 1 ---
bspc desktop -f ^1

# Notificación final
notify-send "✅ Entorno cargado"
